[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
UMBridge = "0ac74fe0-b753-4e62-be71-04a8383fbbef"
